# Generated by Django 4.1.2 on 2022-11-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_chat', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания чата')),
                ('mes_amount', models.IntegerField(default=0, verbose_name='Количество сообщений в чате')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Текст сообщения', max_length=400)),
                ('sent_time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_read', models.DateTimeField(default=False, verbose_name='Прочитано или нет')),
                ('chat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.chat', verbose_name='')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-sent_time',),
            },
        ),
    ]
