# Generated by Django 4.1.2 on 2022-11-16 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_message_remove_messages_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_from_message', to=settings.AUTH_USER_MODEL, verbose_name='Отправлено от'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_to_message', to=settings.AUTH_USER_MODEL, verbose_name='Отправлено кому'),
        ),
        migrations.AddField(
            model_name='chat',
            name='first_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_user_chat', to=settings.AUTH_USER_MODEL, verbose_name='Первый пользователь'),
        ),
        migrations.AddField(
            model_name='chat',
            name='second_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_user_chat', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь'),
        ),
    ]
