# Generated by Django 4.1.2 on 2022-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано или нет'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default='', max_length=400),
        ),
    ]
