# Generated by Django 4.1.2 on 2022-11-17 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_message_sent_from_message_sent_to_chat_first_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники чата'),
        ),
    ]
